# Generated by Django 5.2.3 on 2025-06-26 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('PLAZO_PROCESAL', 'Plazo Procesal'), ('AUDIENCIA', 'Audiencia'), ('REUNION_CLIENTE', 'Reunión con Cliente'), ('TAREA_INTERNA', 'Tarea Interna'), ('OTRO', 'Otro')], default='PLAZO_PROCESAL', max_length=50)),
                ('fecha_hora_vencimiento', models.DateTimeField(help_text='Fecha y hora límite o del evento.')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('recordatorio_activo', models.BooleanField(default=True)),
                ('dias_antes_recordatorio', models.PositiveIntegerField(blank=True, default=1, help_text='Días antes del vencimiento para enviar recordatorio.', null=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plazos_agenda', to='casos.caso')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plazos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plazo o Evento de Agenda',
                'verbose_name_plural': 'Plazos y Eventos de Agenda',
                'ordering': ['fecha_hora_vencimiento'],
            },
        ),
    ]
