# Generated by Django 5.2.3 on 2025-06-26 16:35

import django.db.models.deletion
import documentos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(help_text='Nombre descriptivo del documento.', max_length=255)),
                ('archivo', models.FileField(upload_to=documentos.models.ruta_archivo_documento)),
                ('tipo_documento', models.CharField(blank=True, choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('PRUEBA', 'Prueba Documental'), ('SENTENCIA', 'Sentencia'), ('RESOLUCION', 'Resolución Judicial'), ('ESCRITO_TRAMITE', 'Escrito de Trámite'), ('NOTIFICACION', 'Notificación'), ('RECURSO', 'Recurso'), ('INFORME_PERICIAL', 'Informe Pericial'), ('OTRO', 'Otro')], default='OTRO', max_length=50, null=True)),
                ('fecha_documento', models.DateField(blank=True, help_text='Fecha que figura en el documento (ej: fecha de la sentencia).', null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('metadatos_ia', models.JSONField(blank=True, help_text='Metadatos extraídos por IA (clasificación, entidades, resumen, etc.)', null=True)),
                ('openai_file_id', models.CharField(blank=True, help_text='ID del archivo en OpenAI si se subió para RAG.', max_length=100, null=True)),
                ('texto_extraido', models.TextField(blank=True, help_text='Texto extraído del documento (si aplica y se procesó).', null=True)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cargados', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='casos.caso')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
