# Generated by Django 5.2.3 on 2025-06-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Detalles del error si el procesamiento falló.', null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='processing_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20),
        ),
    ]
