# Generated by Django 5.2.3 on 2026-01-25 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaPlantilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Demanda, Audiencia Incidental, Sentencia', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('dias_termino_sugerido', models.PositiveIntegerField(blank=True, help_text='Días para el siguiente hito', null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPlantilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Amparo Indirecto, Juicio Civil Ordinario', max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInstancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='casos.caso')),
                ('etapa_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows_procesales.etapaplantilla')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows_procesales.workflowplantilla')),
            ],
        ),
        migrations.CreateModel(
            name='HitoProcesal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_cumplimiento', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, null=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows_procesales.etapaplantilla')),
                ('workflow_instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='workflows_procesales.workflowinstancia')),
            ],
        ),
        migrations.AddField(
            model_name='etapaplantilla',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='workflows_procesales.workflowplantilla'),
        ),
    ]
