# Generated by Django 5.2.3 on 2025-06-26 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraccionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('api_utilizada', models.CharField(choices=[('OPENAI_ASSISTANT', 'OpenAI Assistants API'), ('OPENAI_GENERAL', 'OpenAI API (General)'), ('DEEPSEEK', 'Deepseek API'), ('PERPLEXITY', 'Perplexity AI API'), ('OTRA', 'Otra API')], max_length=50)),
                ('prompt_enviado', models.TextField(blank=True, null=True)),
                ('respuesta_recibida', models.TextField(blank=True, null=True)),
                ('archivos_adjuntos_prompt', models.JSONField(blank=True, help_text='IDs de archivos enviados en el prompt, ej: OpenAI file_ids', null=True)),
                ('costo_aproximado', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('duracion_ms', models.PositiveIntegerField(blank=True, help_text='Duración de la llamada a la API en milisegundos', null=True)),
                ('referencia_externa_id', models.CharField(blank=True, help_text='Ej: thread_id, run_id, message_id de OpenAI', max_length=100, null=True)),
                ('metadatos_adicionales', models.JSONField(blank=True, help_text='Cualquier otro metadato relevante de la interacción', null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('error_info', models.TextField(blank=True, null=True)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones_ia', to='casos.caso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción IA',
                'verbose_name_plural': 'Interacciones IA',
                'ordering': ['-timestamp'],
            },
        ),
    ]
