# Generated by Django 5.2.3 on 2026-01-25 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionBoletin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateField()),
                ('resumen_acuerdo', models.TextField()),
                ('contenido_completo', models.TextField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('SISE', 'PJF - SISE (Federal)'), ('CDMX', 'TSJCDMX (Local)'), ('EDOMEX', 'PJEDOMEX (Local)')], max_length=20)),
                ('revisado', models.BooleanField(default=False)),
                ('sugerencia_workflow_paso', models.CharField(blank=True, max_length=255, null=True)),
                ('sugerencia_plazo_dias', models.IntegerField(blank=True, null=True)),
                ('explicacion_ia', models.TextField(blank=True, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_boletin', to='casos.caso')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionFiltro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_expediente', models.CharField(max_length=100)),
                ('origen', models.CharField(choices=[('SISE', 'PJF - SISE (Federal)'), ('CDMX', 'TSJCDMX (Local)'), ('EDOMEX', 'PJEDOMEX (Local)')], max_length=20)),
                ('ultimo_acuerdo_visto', models.CharField(blank=True, max_length=255, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_boletin', to='casos.caso')),
            ],
        ),
    ]
