# Generated by Django 5.2.3 on 2026-01-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletines_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionboletin',
            name='origen',
            field=models.CharField(choices=[('SISE', 'PJF - SISE (Federal)'), ('CDMX', 'TSJCDMX (Local)'), ('EDOMEX', 'PJEDOMEX (Local)'), ('SONORA', 'PJSON (Local)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publicacionfiltro',
            name='origen',
            field=models.CharField(choices=[('SISE', 'PJF - SISE (Federal)'), ('CDMX', 'TSJCDMX (Local)'), ('EDOMEX', 'PJEDOMEX (Local)'), ('SONORA', 'PJSON (Local)')], max_length=20),
        ),
    ]
