[program:lexprocess-celery]
command=/srv/lexprocess/lexprocess_backend/venv/bin/celery -A lexprocess_backend worker -l INFO
directory=/srv/lexprocess/lexprocess_backend
environment=DJANGO_SETTINGS_MODULE="lexprocess_backend.settings.prod"
user=lexprocess
autostart=true
autorestart=true
stopwaitsecs=20
stdout_logfile=/var/log/lexprocess/celery-worker.log
stderr_logfile=/var/log/lexprocess/celery-worker.err

[program:lexprocess-celerybeat]
command=/srv/lexprocess/lexprocess_backend/venv/bin/celery -A lexprocess_backend beat -l INFO
directory=/srv/lexprocess/lexprocess_backend
environment=DJANGO_SETTINGS_MODULE="lexprocess_backend.settings.prod"
user=lexprocess
autostart=true
autorestart=true
stopwaitsecs=20
stdout_logfile=/var/log/lexprocess/celery-beat.log
stderr_logfile=/var/log/lexprocess/celery-beat.err
