# Generated by Django 5.2.3 on 2026-01-25 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jurisdicción',
                'verbose_name_plural': 'Jurisdicciones',
            },
        ),
        migrations.CreateModel(
            name='DiaInhabil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('es_suspension_extraordinaria', models.BooleanField(default=False, help_text='Si es una suspensión no programada (ej. huelga, desastre natural)')),
                ('jurisdiccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_inhabiles', to='calendario_legal.jurisdiccion')),
            ],
            options={
                'verbose_name': 'Día Inhábil',
                'verbose_name_plural': 'Días Inhábiles',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'jurisdiccion')},
            },
        ),
    ]
