# Generated by Django 5.2.3 on 2025-06-26 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('despachos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(choices=[('ABOGADO', 'Abogado'), ('ADMINISTRADOR', 'Administrador de Despacho'), ('PARALEGAL', 'Paralegal')], default='ABOGADO', max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='despachos.despacho')),
            ],
        ),
    ]
