# Generated by Django 5.2.3 on 2025-06-26 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despachos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='despachos.despacho')),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_caso', models.CharField(help_text='Nombre descriptivo o identificador interno del caso.', max_length=255)),
                ('numero_expediente', models.CharField(blank=True, help_text='Número de expediente oficial del juzgado/tribunal.', max_length=100, null=True)),
                ('tipo_proceso', models.CharField(choices=[('CIVIL', 'Civil'), ('PENAL', 'Penal'), ('LABORAL', 'Laboral'), ('ADMINISTRATIVO', 'Administrativo'), ('MERCANTIL', 'Mercantil'), ('FAMILIAR', 'Familiar'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('juzgado_tribunal', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_caso', models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_TRAMITE', 'En Trámite'), ('SUSPENDIDO', 'Suspendido'), ('ARCHIVADO', 'Archivado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('descripcion_breve', models.TextField(blank=True, null=True)),
                ('openai_thread_id', models.CharField(blank=True, help_text='ID del Thread de OpenAI Assistants para este caso.', max_length=100, null=True)),
                ('abogado_asignado', models.ForeignKey(blank=True, limit_choices_to={'profile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados', to=settings.AUTH_USER_MODEL)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='despachos.despacho')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='casos.cliente')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ParteProcesal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rol_en_proceso', models.CharField(help_text='Ej: Demandante, Demandado, Coadyuvante', max_length=100)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_procesales', to='casos.caso')),
            ],
        ),
        migrations.AddConstraint(
            model_name='caso',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_expediente__isnull', False), models.Q(('numero_expediente', ''), _negated=True)), fields=('despacho', 'numero_expediente'), name='unique_expediente_por_despacho'),
        ),
    ]
